### ISSUE TITLE
Proposing a PR to fix a few small typos

### ISSUE THREAD

**Issue by timgates42** [shiyanhui/Young#11]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate and Expected Behaviour

- Examine README.md and observe `shoud`, however expect to see `should`.
- Examine young/setting.py and observe `enviroment`, however expect to see `environment`.
- Examine app/home/document.py and observe `cotent`, however expect to see `content`.

# Notes

Semi-automated issue generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

To avoid wasting CI processing resources a branch with the fix has been
prepared but a pull request has not yet been created. A pull request fixing
the issue can be prepared from the link below, feel free to create it or
request @timgates42 create the PR. Alternatively if the fix is undesired please
close the issue with a small comment about the reasoning.

https://github.com/timgates42/Young/pull/new/bugfix_typos

Thanks.

**Comment by shiyanhui** [comment]
Thanks.
